#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains 
# a custom header (on web-01 and web-02)
# The name of the custom HTTP header must be X-Served-By
# The value of the custom HTTP header must be the hostname of the server Nginx 

sudo apt-get update
sudo apt-get install -y Nginx

mkdir -p /var/www/html
touch /var/www/html/index.html
echo "Hello World" > /var/www/html/index.html
touch /var/www/html/404.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

printf %s "server {
	listen 80 default_server;
	listen[::]:80 default_server;;
	add_header X-Served-By $HOSTNAME;
	root /var/ww/html
	index index.html index.htm;

	location /redirect_me {
        return 301 http://cuberule.com/;
    }
	error_page 404/404.html
	location /404 {
      root /var/www/html;
      internal;
    }
}" > /etc/nginx/sites-available/default

sevice nginx restart
